
## Loading Data
file1<-"DataImported/summarySCC_PM25.rds"
file2<- "DataImported/Source_Classification_Code.rds"
NEI <- readRDS(file1)
SCC <- readRDS(file2)


## Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008?

dev.off()

## extracting codes related to combustions using coal 
combCodes<-SCC[grepl("Coal",SCC$Short.Name)&grepl("Comb",SCC$Short.Name),]

## extracting data related to evolution of PM2.5 generated by coal combustion-related sources 
dataCombCoal<-subset(NEI, SCC %in% combCodes$SCC)
dataCombCoal$year<- factor(dataCombCoal$year)

## computing the sum coal's combustions emissions by year
SommeCombCoal<-tapply(dataCombCoal$Emissions,dataCombCoal$year,sum,na.rm = TRUE)
dates<-strtoi(names(SommeCombCoal))

png("DataExported/plot4.png")
par(mfrow=c(1,2))
plot(dates,log10(SommeCombCoal) , type="o" ,ylab="total sum of PM2.5 (Log10 Scale)" , xlab = "years" , col="blue")
title(main="PM2.5 Combustion using coal in USA ", col.main="red", font.main=4)
nrow(dataCombCoal)
dev.off()